### ISSUE TITLE
Undefined 'ends' object

### ISSUE THREAD

**Issue by themudo** [kmceres/Mbovis_pangenome#1]
Hi.
I am trying to reproduce this analysis with a M. bovis dataset and I stumbled upon a bug on the 'process_Reis_and_Cunha_pangenome.R' script, when it reaches line 58. I can't figure out what the 'ends' dataset is supposed to be, as it is not defined before. Is it one of the datasets previously generated in the script, but with inconsistent naming? Or perhaps something else? I appreciate any hint on this.

**Comment by kmceres** [comment]
Sorry about that! You're right, I misnamed a variable. Check the most recent version of 'process_Reis_and_Cunha_pangenome.R' and let me know if you have any other issues.
